[theme]
primaryColor="#2B4696"
backgroundColor= "#fff"
secondaryBackgroundColor="#b6cfd6"
textColor="#000000"
font="sans serif"

[server]
enableXsrfProtection = false
enableCORS = false
enableWebsocketCompression = false
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
